---
deployment:
  tasks:
    - export DEPLOYPATH=/home/u1807837/absensistkipus
    - /bin/cp -R * $DEPLOYPATH
    - /bin/chmod -R 775 $DEPLOYPATH/storage $DEPLOYPATH/bootstrap/cache
    - /usr/local/bin/php $DEPLOYPATH/artisan migrate --force
    - /usr/local/bin/php $DEPLOYPATH/artisan storage:link
    - /usr/local/bin/php $DEPLOYPATH/artisan config:cache
    - /usr/local/bin/php $DEPLOYPATH/artisan route:cache
    - /usr/local/bin/php $DEPLOYPATH/artisan view:cache
